font_size 12
background_opacity 0.7
confirm_os_window_close 0
allow_images yes

foreground #ffffff
background #000000

color0  #000000
color8  #2a2a2a

color1  #aaaaaa
color9  #ffffff

color2  #bbbbbb
color10 #ffffff

color3  #888888
color11 #cccccc

color4  #777777
color12 #dddddd

color5  #666666
color13 #eeeeee

color6  #555555
color14 #f5f5f5

color7  #cccccc
color15 #ffffff
